export { Burger } from "./Burger";
export { Link } from "./Link";
export { Logo } from "./Logo";
export { Button } from './Button'
export { Title } from './Title'
export { Text } from './Text'
export { Icon } from './Icon';
export { Langs } from './Langs'
export { GDPR } from "./GDPR";
export { Container } from './Container'