export { Footer } from "./Footer";
export { Header } from "./Header";
export { Hero } from "./Hero";
export { Steps } from "./Steps"
export { Toolbox } from './Toolbox'
export { TrendingAssets } from './Assets'
export { Devices } from './Devices'
export { About } from './About'
export { InsideHeader } from './InsideHeader';
export { InsideFooter } from './InsideFooter'